[2025-04-12T10:18:36.502+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-12T10:18:36.563+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pollen_ingestion_dag.ingest scheduled__2025-04-11T08:00:00+00:00 [queued]>
[2025-04-12T10:18:36.590+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pollen_ingestion_dag.ingest scheduled__2025-04-11T08:00:00+00:00 [queued]>
[2025-04-12T10:18:36.591+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-12T10:18:36.616+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest> on 2025-04-11 08:00:00+00:00
[2025-04-12T10:18:36.631+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=205) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-12T10:18:36.637+0000] {standard_task_runner.py:72} INFO - Started process 216 to run task
[2025-04-12T10:18:36.647+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pollen_ingestion_dag', 'ingest', 'scheduled__2025-04-11T08:00:00+00:00', '--job-id', '768', '--raw', '--subdir', 'DAGS_FOLDER/pollen_ingestion_dag.py', '--cfg-path', '/tmp/tmp07bi4pmb']
[2025-04-12T10:18:36.661+0000] {standard_task_runner.py:105} INFO - Job 768: Subtask ingest
[2025-04-12T10:18:36.804+0000] {task_command.py:467} INFO - Running <TaskInstance: pollen_ingestion_dag.ingest scheduled__2025-04-11T08:00:00+00:00 [running]> on host e1fcb75fb946
[2025-04-12T10:18:37.025+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='beni' AIRFLOW_CTX_DAG_ID='pollen_ingestion_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-11T08:00:00+00:00'
[2025-04-12T10:18:37.026+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-12T10:18:37.055+0000] {logging_mixin.py:190} INFO - ❌ Failed to fetch pollen data: HTTPSConnectionPool(host='opendata.dwd.de', port=443): Max retries exceeded with url: /climate_environment/health/alerts/s31fg.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff7c5a06e0>: Failed to resolve 'opendata.dwd.de' ([Errno -2] Name or service not known)"))
[2025-04-12T10:18:37.056+0000] {logging_mixin.py:190} INFO - ❌ Region with ID 123 not found.
[2025-04-12T10:18:37.056+0000] {pollen_ingestion_dag.py:31} WARNING - ⚠️ No pollen data parsed for region ID 123.
[2025-04-12T10:18:37.057+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-12T10:18:37.082+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-12T10:18:37.085+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=pollen_ingestion_dag, task_id=ingest, run_id=scheduled__2025-04-11T08:00:00+00:00, execution_date=20250411T080000, start_date=20250412T101836, end_date=20250412T101837
[2025-04-12T10:18:37.155+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-12T10:18:37.177+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-12T10:18:37.179+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
