[2025-04-11T07:47:30.234+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T07:47:30.248+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_forecast_ingestion_dag.clean scheduled__2025-04-10T22:00:00+00:00 [queued]>
[2025-04-11T07:47:30.253+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_forecast_ingestion_dag.clean scheduled__2025-04-10T22:00:00+00:00 [queued]>
[2025-04-11T07:47:30.254+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-11T07:47:30.262+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): clean> on 2025-04-10 22:00:00+00:00
[2025-04-11T07:47:30.265+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T07:47:30.266+0000] {standard_task_runner.py:72} INFO - Started process 76 to run task
[2025-04-11T07:47:30.266+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_forecast_ingestion_dag', 'clean', 'scheduled__2025-04-10T22:00:00+00:00', '--job-id', '703', '--raw', '--subdir', 'DAGS_FOLDER/weather_forecast_ingestion_dag.py', '--cfg-path', '/tmp/tmpho3gknpc']
[2025-04-11T07:47:30.268+0000] {standard_task_runner.py:105} INFO - Job 703: Subtask clean
[2025-04-11T07:47:30.294+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_forecast_ingestion_dag.clean scheduled__2025-04-10T22:00:00+00:00 [running]> on host 98acdd3c69ae
[2025-04-11T07:47:30.342+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='beni' AIRFLOW_CTX_DAG_ID='weather_forecast_ingestion_dag' AIRFLOW_CTX_TASK_ID='clean' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T22:00:00+00:00'
[2025-04-11T07:47:30.343+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-11T07:47:30.783+0000] {logging_mixin.py:190} INFO - üóëÔ∏è Deleting outdated forecast: weather_forecast/bamberg/2025-04-11T0600.json
[2025-04-11T07:47:30.831+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Could not parse/delete weather_forecast/bamberg/2025-04-11T0600.json: 404 DELETE https://storage.googleapis.com/storage/v1/b/gooutside-raw/o/weather_forecast%2Fbamberg%2F2025-04-11T0600.json?generation=1744322489573648&prettyPrint=false: No such object: gooutside-raw/weather_forecast/bamberg/2025-04-11T0600.json
[2025-04-11T07:47:30.831+0000] {logging_mixin.py:190} INFO - üóëÔ∏è Deleting outdated forecast: weather_forecast/bamberg/2025-04-11T0700.json
[2025-04-11T07:47:30.931+0000] {logging_mixin.py:190} INFO - ‚ö†Ô∏è Could not parse/delete weather_forecast/bamberg/2025-04-11T0700.json: 404 DELETE https://storage.googleapis.com/storage/v1/b/gooutside-raw/o/weather_forecast%2Fbamberg%2F2025-04-11T0700.json?generation=1744322489928335&prettyPrint=false: The specified key does not exist.
[2025-04-11T07:47:30.932+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T07:47:30.945+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-11T07:47:30.945+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_forecast_ingestion_dag, task_id=clean, run_id=scheduled__2025-04-10T22:00:00+00:00, execution_date=20250410T220000, start_date=20250411T074730, end_date=20250411T074730
[2025-04-11T07:47:30.987+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-11T07:47:31.000+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-11T07:47:31.001+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
