[2025-04-07T01:41:34.668+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-07T01:41:34.681+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-07T00:00:00+00:00 [queued]>
[2025-04-07T01:41:34.690+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-07T00:00:00+00:00 [queued]>
[2025-04-07T01:41:34.690+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-07T01:41:34.698+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): ingest> on 2025-04-07 00:00:00+00:00
[2025-04-07T01:41:34.702+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=287) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-07T01:41:34.704+0000] {standard_task_runner.py:72} INFO - Started process 289 to run task
[2025-04-07T01:41:34.704+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_ingestion_dag', 'ingest', 'scheduled__2025-04-07T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/weather_ingestion_dag.py', '--cfg-path', '/tmp/tmp6mdd0dtc']
[2025-04-07T01:41:34.707+0000] {standard_task_runner.py:105} INFO - Job 192: Subtask ingest
[2025-04-07T01:41:34.764+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_ingestion_dag.ingest scheduled__2025-04-07T00:00:00+00:00 [running]> on host 242fb041fbeb
[2025-04-07T01:41:34.858+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='beni' AIRFLOW_CTX_DAG_ID='weather_ingestion_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-04-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-07T00:00:00+00:00'
[2025-04-07T01:41:34.860+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-07T01:41:35.544+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T06:00:00+02:00.json
[2025-04-07T01:41:35.902+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T07:00:00+02:00.json
[2025-04-07T01:41:36.242+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T08:00:00+02:00.json
[2025-04-07T01:41:36.600+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T09:00:00+02:00.json
[2025-04-07T01:41:36.970+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T10:00:00+02:00.json
[2025-04-07T01:41:37.314+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T11:00:00+02:00.json
[2025-04-07T01:41:38.643+0000] {connectionpool.py:868} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1010)'))': /token
[2025-04-07T01:41:39.051+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T12:00:00+02:00.json
[2025-04-07T01:41:39.430+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T13:00:00+02:00.json
[2025-04-07T01:41:39.779+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T14:00:00+02:00.json
[2025-04-07T01:41:40.244+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T15:00:00+02:00.json
[2025-04-07T01:41:40.615+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T16:00:00+02:00.json
[2025-04-07T01:41:40.969+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T17:00:00+02:00.json
[2025-04-07T01:41:41.467+0000] {logging_mixin.py:190} INFO - ✅ Saved: gs://gooutside-raw/weather/bamberg/2025-04-07T18:00:00+02:00.json
[2025-04-07T01:41:41.469+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-07T01:41:41.489+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-07T01:41:41.490+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_ingestion_dag, task_id=ingest, run_id=scheduled__2025-04-07T00:00:00+00:00, execution_date=20250407T000000, start_date=20250407T014134, end_date=20250407T014141
[2025-04-07T01:41:41.536+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-07T01:41:41.549+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-07T01:41:41.550+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
